### ISSUE TITLE
Not working for nbd 3.1 or newer

### ISSUE THREAD

**Issue by void-main** [soundsrc/s3nbd#1]
Hi guys, seems s3nbd is not compatible with newer version of NBD.

## Environments
- CentOS Version: centos-release-7-3.1611.el7.centos.x86_64
- Kernel Version: 3.10.0-693.11.6.el7.x86_64
- nbd-client Version: 3.17

## Steps
1. Follow the steps to compile and install NBD kernel module
2. Compile and install NBD client
3. Compile and install s3nbd
4. Start s3nbd server, it's working
5. Try to connect to s3nbd with nbd-client as described in [this documentation](https://www.sagaforce.com/sound/s3nbd/), and error occurred: 

```
[root@vm10-1-0-10 ~]# nbd-client bs=4096 localhost 5353 /dev/nbd0
WARNING: old-style command-line argument encountered. This is deprecated.
Warning: the oldstyle protocol is no longer supported.
This method now uses the newstyle protocol with a default export
Negotiation: .Error: It looks like you're trying to connect to an oldstyle server. This is no longer supported since nbd 3.10.
Exiting.
```

Seems that handshake process failed. Any plan to fix this issue?

**Comment by soundsrc** [comment]
Hello there! This project has not been maintained since 2007. A fix is unlikely. I encourage you to seek alternative projects which may provide the same functionality. Have a good day!

**Comment by void-main** [comment]
Cool, thanks @soundsrc . Any recommendations? I found s3blkdev, any comments on that project?

**Comment by soundsrc** [comment]
I have not seen that project before and therefore unable to comment. It does appear to do something similar. I say give it a try!

**Comment by void-main** [comment]
Thanks for your comment!
